title: "~/.thiagorls"
description: "Hi, I am an electrical engineer, passionate about hardware, software, coffee and solving problems I don’t need to solve."
base_url: "https://thiagorls.com"
author: "Thiago Rodrigues"
